#!/bin/bash

# 1,1,1,4,99,5,6,0,99 -> 30,1,1,4,2,5,6,0,99

# First four positions done!:
# start at [0] done
# read [1] and [2]
# add position [1] and position [2]
# read value [3]
# replace [3] with sum [1] and [2]

# start at [0]+4
# read [1]+4 and [2]+4
# multiply position [1] and position [2]
# read value [3]
# replace [3] with sum [1] and [2]

declare -a opcode_list

# format input value later
#opcode_list=("${test_optcode_string//,/$'\n'}")
#echo "${opcode_list[8]}"

opcode_list=(1
12
2
3
1
1
2
3
1
3
4
3
1
5
0
3
2
10
1
19
1
6
19
23
2
23
6
27
1
5
27
31
1
31
9
35
2
10
35
39
1
5
39
43
2
43
10
47
1
47
6
51
2
51
6
55
2
55
13
59
2
6
59
63
1
63
5
67
1
6
67
71
2
71
9
75
1
6
75
79
2
13
79
83
1
9
83
87
1
87
13
91
2
91
10
95
1
6
95
99
1
99
13
103
1
13
103
107
2
107
10
111
1
9
111
115
1
115
10
119
1
5
119
123
1
6
123
127
1
10
127
131
1
2
131
135
1
135
10
0
99
2
14
0
0
)

declare current_starting=0

for index_in_list in "${!opcode_list[@]}";
	do if [ "$index_in_list" == "$current_starting" ] && [ "${opcode_list["$index_in_list"]}" == 1 ]
		then
		  echo "============"
		  echo "Add"
      echo "============"

      echo "Values of the first four indexes "
		  echo "${opcode_list["$current_starting"]}";
      echo "${opcode_list["$current_starting"+1]}";
      echo "${opcode_list["$current_starting"+2]}";
      echo "${opcode_list["$current_starting"+3]}";

      value_of_index_1="${opcode_list["$current_starting"+1]}"
      value_of_index_2="${opcode_list["$current_starting"+2]}"

      #Use value as index position
      #Read the value of the index position
      position_1="${opcode_list[value_of_index_1]}"
      position_2="${opcode_list[value_of_index_2]}"

      #add position [1] and position [2]
      sum_1_2=$(("$position_1"+"$position_2"))

      value_of_index_3="${opcode_list["$current_starting"+3]}"
      #use value 3 as index to be changed to sum_1_2
      opcode_list[value_of_index_3]="$sum_1_2"

      current_starting=$(("$current_starting"+4))

  elif [ "$index_in_list" == "$current_starting" ] && [ "${opcode_list["$index_in_list"]}" == 2 ];
    then
      echo "============"
      echo "Multiply"
      echo "============"

      echo "Values of the first four indexes "
		  echo "${opcode_list["$current_starting"]}";
      echo "${opcode_list["$current_starting"+1]}";
      echo "${opcode_list["$current_starting"+2]}";
      echo "${opcode_list["$current_starting"+3]}";

      value_of_index_1="${opcode_list["$current_starting"+1]}"
      value_of_index_2="${opcode_list["$current_starting"+2]}"

      #Use value as index position
      #Read the value of the index position
      position_1="${opcode_list[value_of_index_1]}"
      position_2="${opcode_list[value_of_index_2]}"

      #add position [1] and position [2]
      product_1_2=$(("$position_1"*"$position_2"))

      value_of_index_3="${opcode_list["$current_starting"+3]}"
      #use value 3 as index to be changed to sum_1_2
      opcode_list[value_of_index_3]="$product_1_2"

      current_starting=$(("$current_starting"+4))

  elif [ "$index_in_list" == "$current_starting" ] && [ "${opcode_list["$index_in_list"]}" == 99 ];
    then
      echo "Stop program"

	fi
done

echo ""
echo "Adjusted value"
echo "${opcode_list[@]}"

echo ""
echo "Current starting position"
echo "$current_starting"

echo ""
echo "Passed $((current_starting/4)) set of four"